version: '3'

services:
  web:
    image: ${PEOPLE_SEARCH_IMAGE:-536333801959.dkr.ecr.us-east-1.amazonaws.com/people-search}:${PEOPLE_SEARCH_TAG:-latest}
    ports:
      - 9080:8080
      - 9443:8443
    volumes:
      - ${SECRETS_DIR:-./secrets}:/run/secrets:ro
    networks:
      - frontend
      - db

  db:
    image: ${PEOPLE_DB_IMAGE:-536333801959.dkr.ecr.us-east-1.amazonaws.com/people-db}:${PEOPLE_DB_TAG:-latest}
    ports:
      - 3306
    volumes:
      - ${SECRETS_DIR:-./secrets}:/run/secrets:ro
    networks:
      - db

  sync:
    image: ${PEOPLE_SYNC_IMAGE:-536333801959.dkr.ecr.us-east-1.amazonaws.com/people-sync}:${PEOPLE_SYNC_TAG:-latest}
    ports:
      - 9081:8080
      - 9444:8443
    volumes:
      - ${SECRETS_DIR:-./secrets}:/run/secrets:ro
    networks:
      - frontend
      - db

networks:
  frontend:
    driver: bridge
  db:
    driver: bridge

      