version: 0.2

run-as: root

env:
  variables:
    DOCKER_REGISTRY: "536333801959.dkr.ecr.us-east-1.amazonaws.com"
  parameter-store:
    MYSQL_ROOT_PASSWORD: "/PeopleDB-prod-backup-image/MYSQL_ROOT_PASSWORD"
    MYSQL_PASSWORD: "/PeopleDB-prod-backup-image/MYSQL_PASSWORD"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
  build:
    commands:
      - chmod +x db/*.sh
      - aws s3 cp s3://cisl-aws-hcm-people-sql/people.sql PEOPLEDB.sql
      - db/build.sh <PEOPLEDB.sql
      - db/tag-push.sh

