#!/bin/bash
SECRETS_DIR="${SECRETS_DIR:-/run/secrets}"
SECRETS_FILE="${SECRETS_DIR}/pdb.txt"
MYSQL=${MYSQL:-/usr/bin/mysql}

if [ -f "${SECRETS_FILE}" ] ; then
    . "${SECRETS_FILE}" || exit 1
fi
MYSQL_DATABASE=${MYSQL_DATABASE:-people}
MYSQL_TCP_PORT=${PDB_PORT:-3306}
MYSQL_HOST=${PDB_HOST:-db}
MYSQL_USER=${PDB_LOGIN:-people}
MYSQL_PWD=${PDB_PASSWORD}
export MYSQL_DATABASE MYSQL_TCP_PORT MYSQL_HOST MYSQL_USER
if [ ":${PDB_PASSWORD}" != ":" ] ; then
    export MYSQL_PWD
fi

${MYSQL} -u ${MYSQL_USER} -p ${MYSQL_PASSWORD} "$@" ${MYSQL_DATABASE}
